spring:
  application:
    name: moonment-backend

  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: postgres.idpxmyxsstkhneqkeuda
    password: Moonment1234!

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 539950730703-fo2t0i1ahlo0oesqlsc4gofei7qclkhk.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true